[package]
name = "primes"
version = "0.0.1"
authors = ["Caio O Campos <caio.campos1204@gmail.com.br>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true