language: node_js
node_js:
  - "12"
dist: bionic
sudo: required

branches:
  only:
  - master

before_install:
  - curl https://sh.rustup.rs -sSf | bash -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - npm run build-wasm

before_script:
  - npm install -g @angular/cli

jobs:
  include:
    - stage: pages
      script:
        - ng lint
        - ng build --prod --base-href /primes/
        - cd dist/primes
        - cp index.html 404.html
        - cd ../..
      deploy: &pages
        provider: pages
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: dist/primes
        on:
          branch: master
    - stage: npm
      script: skip
      before_deploy:
        - cd primes-rs/pkg
        - rm -f .gitignore
      deploy: &npm
        provider: npm
        skip_cleanup: true
        api_key: $NPM_TOKEN
        email: "caio.campos1204@gmail.com"
        tag: next
        on:
          branch: master