name: RustWasm CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'primes-rs/**'
      - '!.github/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Run tests
      working-directory: ./primes-rs
      run: cargo test --verbose
    - name: Build lib
      run: sh ./build-lib.sh
